import { useState, useEffect } from 'react'
import { FiAlertTriangle, FiCheckCircle, FiDownload, FiFileText, FiArrowRight, FiArrowLeft, FiStar, FiInfo, FiEye, FiUser } from 'react-icons/fi'

export default function CVEvaluator({ cvData, onUseOriginal, onUseTemplate }) {
  const [evaluation, setEvaluation] = useState(null)
  const [loading, setLoading] = useState(true)
  const [selectedTemplate, setSelectedTemplate] = useState(null)
  const [previewTemplate, setPreviewTemplate] = useState(null)

  useEffect(() => {
    const evaluate = async () => {
      try {
        const resp = await fetch('/api/evaluate-cv', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ cvData }),
        })
        if (!resp.ok) throw new Error('Evaluation failed')
        setEvaluation(await resp.json())
      } catch {
        setEvaluation({
          qualityScore: 70,
          isPoorQuality: false,
          issues: [],
          templates: [],
          message: 'Could not fully evaluate your CV. You can continue with your current CV.',
        })
      } finally {
        setLoading(false)
      }
    }
    evaluate()
  }, [cvData])

  const downloadPDF = (template) => {
    const { jsPDF } = window.jspdf
    const doc = new jsPDF('p', 'mm', 'a4')
    const pageW = 210
    const margin = 18
    const contentW = pageW - margin * 2
    let y = margin

    const header = template.sections.find(s => s.title === 'header')?.content || {}

    // Header bar
    doc.setFillColor(108, 92, 231)
    doc.rect(0, 0, pageW, 38, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text(header.name || 'Your Name', margin, 18)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(header.role || '', margin, 25)
    doc.setFontSize(8)
    const contactParts = [header.email, header.phone, header.location].filter(Boolean)
    doc.text(contactParts.join('  |  '), margin, 32)

    y = 46

    for (const section of template.sections) {
      if (section.title === 'header') continue
      if (!section.content || (Array.isArray(section.content) && section.content.length === 0)) continue

      if (y > 260) { doc.addPage(); y = margin }

      // Section heading
      doc.setFillColor(108, 92, 231)
      doc.rect(margin, y, contentW, 0.5, 'F')
      y += 4
      doc.setTextColor(108, 92, 231)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.text(section.heading || section.title.toUpperCase(), margin, y)
      y += 6

      doc.setTextColor(50, 50, 50)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)

      if (Array.isArray(section.content)) {
        for (const item of section.content) {
          if (y > 275) { doc.addPage(); y = margin }
          const lines = doc.splitTextToSize(`• ${item}`, contentW)
          doc.text(lines, margin, y)
          y += lines.length * 4.2 + 1
        }
      } else if (typeof section.content === 'string') {
        const lines = doc.splitTextToSize(section.content, contentW)
        for (const line of lines) {
          if (y > 275) { doc.addPage(); y = margin }
          doc.text(line, margin, y)
          y += 4.2
        }
      }
      y += 4
    }

    // Footer
    const totalPages = doc.internal.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i)
      doc.setFontSize(7)
      doc.setTextColor(150, 150, 150)
      doc.text(`Generated by AI Job Application Assistant`, margin, 290)
      doc.text(`Page ${i} of ${totalPages}`, pageW - margin - 20, 290)
    }

    doc.save(`${(header.name || 'CV').replace(/\s+/g, '_')}_${template.name.replace(/\s+/g, '_')}.pdf`)
  }

  if (loading) {
    return (
      <div className="glass-card p-12 text-center space-y-4">
        <div className="w-16 h-16 mx-auto border-4 border-primary-500/30 border-t-primary-500 rounded-full animate-spin" />
        <p className="text-white/60">Evaluating your CV quality...</p>
      </div>
    )
  }

  if (!evaluation) return null

  // GOOD CV — just show score and tips, let them continue
  if (!evaluation.isPoorQuality) {
    return (
      <div className="space-y-6">
        <div className="text-center space-y-2">
          <h2 className="text-2xl sm:text-3xl font-bold text-white">
            CV <span className="gradient-text">Evaluation</span>
          </h2>
          <p className="text-white/50">{evaluation.message}</p>
        </div>

        <div className="glass-card p-6 text-center">
          <div className="relative w-24 h-24 mx-auto mb-3">
            <svg className="w-24 h-24 -rotate-90" viewBox="0 0 100 100">
              <circle cx="50" cy="50" r="42" stroke="rgba(255,255,255,0.05)" strokeWidth="8" fill="none" />
              <circle cx="50" cy="50" r="42" stroke="url(#evalGrad)" strokeWidth="8" fill="none"
                strokeDasharray={`${evaluation.qualityScore * 2.64} 264`} strokeLinecap="round" />
              <defs>
                <linearGradient id="evalGrad" x1="0%" y1="0%" x2="100%" y2="0%">
                  <stop offset="0%" stopColor="#00b894" />
                  <stop offset="100%" stopColor="#00cec9" />
                </linearGradient>
              </defs>
            </svg>
            <div className="absolute inset-0 flex items-center justify-center">
              <span className="text-2xl font-bold text-white">{evaluation.qualityScore}</span>
            </div>
          </div>
          <p className="text-white/40 text-sm">CV Quality Score</p>
        </div>

        {evaluation.issues.length > 0 && (
          <div className="glass-card p-5">
            <h3 className="text-white font-semibold mb-3 flex items-center gap-2">
              <FiInfo className="w-5 h-5 text-yellow-400" /> Improvement Tips
            </h3>
            <div className="space-y-2">
              {evaluation.issues.map((issue, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-white/5 rounded-xl">
                  {issue.severity === 'critical'
                    ? <FiAlertTriangle className="w-4 h-4 text-red-400 mt-0.5 shrink-0" />
                    : <FiInfo className="w-4 h-4 text-yellow-400 mt-0.5 shrink-0" />}
                  <p className="text-white/70 text-sm">{issue.message}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        <button onClick={onUseOriginal} className="btn-primary w-full flex items-center justify-center gap-2 py-4 text-lg">
          Continue With Your CV <FiArrowRight className="w-5 h-5" />
        </button>
      </div>
    )
  }

  // POOR CV — show warning + templates + option to keep original
  return (
    <div className="space-y-6">
      <div className="text-center space-y-2">
        <h2 className="text-2xl sm:text-3xl font-bold text-white">
          CV <span className="gradient-text">Needs Improvement</span>
        </h2>
        <p className="text-white/50">{evaluation.message}</p>
      </div>

      <div className="glass-card p-5 border border-yellow-500/20 bg-yellow-500/5">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-xl bg-yellow-500/20 flex items-center justify-center shrink-0">
            <FiAlertTriangle className="w-5 h-5 text-yellow-400" />
          </div>
          <div>
            <h3 className="text-white font-semibold">Your CV scored {evaluation.qualityScore}/100</h3>
            <p className="text-white/50 text-sm mt-1">
              {evaluation.issues.filter(i => i.severity === 'critical').length} critical issues found.
              We have generated 3 improved templates using your information. You can download any of them as a PDF, or continue with your original CV.
            </p>
          </div>
        </div>
      </div>

      {evaluation.issues.length > 0 && (
        <div className="glass-card p-5">
          <h3 className="text-white font-semibold mb-3 text-sm">Issues Found:</h3>
          <div className="space-y-2">
            {evaluation.issues.map((issue, i) => (
              <div key={i} className="flex items-start gap-2 text-sm">
                {issue.severity === 'critical'
                  ? <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 shrink-0" />
                  : <span className="w-1.5 h-1.5 rounded-full bg-yellow-400 mt-1.5 shrink-0" />}
                <span className="text-white/60">{issue.message}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {evaluation.templates.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-white font-semibold flex items-center gap-2">
            <FiStar className="w-5 h-5 text-primary-400" /> Choose a Template
          </h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {evaluation.templates.map(template => (
              <div key={template.id}
                className={`glass-card p-5 cursor-pointer transition-all ${
                  selectedTemplate === template.id
                    ? 'border-primary-500 bg-primary-500/10 ring-1 ring-primary-500/30'
                    : 'hover:border-white/20'
                }`}
                onClick={() => setSelectedTemplate(template.id)}
              >
                <div className="flex items-center gap-2 mb-2">
                  <FiFileText className="w-5 h-5 text-primary-400" />
                  <h4 className="text-white font-semibold text-sm">{template.name}</h4>
                </div>
                <p className="text-white/40 text-xs mb-4">{template.description}</p>

                <div className="space-y-1.5 mb-4">
                  {template.sections.filter(s => s.title !== 'header').slice(0, 4).map((s, i) => (
                    <div key={i} className="flex items-center gap-2 text-white/30 text-xs">
                      <div className="w-1 h-1 rounded-full bg-primary-400" />
                      {s.heading}
                    </div>
                  ))}
                </div>

                <div className="flex gap-2">
                  <button
                    onClick={(e) => { e.stopPropagation(); setPreviewTemplate(template) }}
                    className="flex-1 py-2 px-3 rounded-lg bg-white/5 text-white/60 text-xs flex items-center justify-center gap-1 hover:bg-white/10 transition-colors"
                  >
                    <FiEye className="w-3 h-3" /> Preview
                  </button>
                  <button
                    onClick={(e) => { e.stopPropagation(); downloadPDF(template) }}
                    className="flex-1 py-2 px-3 rounded-lg bg-primary-500/20 text-primary-300 text-xs flex items-center justify-center gap-1 hover:bg-primary-500/30 transition-colors"
                  >
                    <FiDownload className="w-3 h-3" /> Download
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="flex flex-col sm:flex-row gap-3">
        <button
          onClick={() => {
            if (selectedTemplate) {
              const tmpl = evaluation.templates.find(t => t.id === selectedTemplate)
              onUseTemplate(tmpl)
            }
          }}
          disabled={!selectedTemplate}
          className={`flex-1 py-4 px-6 rounded-xl font-semibold flex items-center justify-center gap-2 transition-all ${
            selectedTemplate
              ? 'bg-gradient-to-r from-primary-500 to-cyan-500 text-white shadow-lg shadow-primary-500/25'
              : 'bg-white/5 text-white/20 cursor-not-allowed'
          }`}
        >
          <FiFileText className="w-5 h-5" /> Use Selected Template
        </button>

        <button
          onClick={onUseOriginal}
          className="flex-1 py-4 px-6 rounded-xl font-semibold flex items-center justify-center gap-2 bg-white/5 text-white/60 border border-white/10 hover:bg-white/10 transition-all"
        >
          <FiUser className="w-5 h-5" /> Keep My Original CV <FiArrowRight className="w-4 h-4" />
        </button>
      </div>

      {/* Preview Modal */}
      {previewTemplate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
          onClick={() => setPreviewTemplate(null)}>
          <div className="bg-gray-900 rounded-2xl max-w-lg w-full max-h-[80vh] overflow-y-auto p-6 space-y-4"
            onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between">
              <h3 className="text-white font-bold text-lg">{previewTemplate.name}</h3>
              <button onClick={() => setPreviewTemplate(null)} className="text-white/40 hover:text-white text-sm">Close</button>
            </div>

            <div className="bg-white rounded-xl p-6 text-gray-800 text-sm space-y-4">
              {previewTemplate.sections.map((s, i) => {
                if (s.title === 'header') {
                  return (
                    <div key={i} className="border-b-2 border-primary-500 pb-3">
                      <h2 className="text-xl font-bold text-primary-600">{s.content.name}</h2>
                      <p className="text-gray-500 text-xs">{s.content.role}</p>
                      <p className="text-gray-400 text-xs mt-1">{[s.content.email, s.content.phone, s.content.location].filter(Boolean).join(' | ')}</p>
                    </div>
                  )
                }
                if (!s.content || (Array.isArray(s.content) && s.content.length === 0)) return null
                const items = Array.isArray(s.content) ? s.content : [s.content]
                return (
                  <div key={i}>
                    <h3 className="font-bold text-primary-600 text-xs uppercase tracking-wider mb-1">{s.heading}</h3>
                    {items.map((item, j) => (
                      <p key={j} className="text-gray-600 text-xs ml-2">{'\u2022'} {item}</p>
                    ))}
                  </div>
                )
              })}
            </div>

            <div className="flex gap-2">
              <button onClick={() => { downloadPDF(previewTemplate) }}
                className="flex-1 btn-primary py-2 flex items-center justify-center gap-2 text-sm">
                <FiDownload className="w-4 h-4" /> Download PDF
              </button>
              <button onClick={() => { setSelectedTemplate(previewTemplate.id); setPreviewTemplate(null) }}
                className="flex-1 btn-secondary py-2 flex items-center justify-center gap-2 text-sm">
                <FiCheckCircle className="w-4 h-4" /> Select This Template
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
